---

- name: Create Unifi directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ unifi_docker_data_folder }}"
    - "{{ unifi_docker_log_folder }}"
    - "{{ unifi_docker_cert_folder }}"
    - "{{ unifi_docker_init_folder }}"

- name: Create Unifi container
  docker_container:
    name: unifi
    image: "jacobalberty/unifi:{{ unifi_docker_tag }}"
    state: started
    restart_policy: unless-stopped
    init: true
    network_mode: host
    published_ports:
      - '3478:3478/udp'
      - '8080:8080'
      - '8443:8443'
      - '8880:8880'
      - '6789:6789'
      - '10001:10001/udp'
    volumes:
      - "{{ unifi_docker_data_folder }}:/unifi/data"
      - "{{ unifi_docker_log_folder }}:/unifi/log"
      - "{{ unifi_docker_cert_folder }}:/unifi/cert"
      - "{{ unifi_docker_init_folder }}:/unifi/init.d"
    env:
      TZ: "{{ unifi_docker_tz }}"
